name    'branan-s3file'
version '1.0.0'
source  'https://github.com/branan/puppet-module-s3file'
author  'Branan Purvine-Riley'
license 'Apache License 2.0'
summary 'S3 File Synchronization'
description 'Keep a file up-to-date with an S3 source'
project_page 'https://github.com/branan/puppet-module-s3file'
